// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIX6BPWg4vO25X-3WuvREdArIIOU2lyK4',
    appId: '1:424296832329:web:abbcff50e61c5ffce64e98',
    messagingSenderId: '424296832329',
    projectId: 'simple-distributed-database',
    authDomain: 'simple-distributed-database.firebaseapp.com',
    databaseURL: 'https://simple-distributed-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simple-distributed-database.firebasestorage.app',
    measurementId: 'G-LXW241NRWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjQAxHIyvdG-DAYiY3_Rn9aBrFMXAkJds',
    appId: '1:424296832329:android:f85602b9ccbf951ce64e98',
    messagingSenderId: '424296832329',
    projectId: 'simple-distributed-database',
    databaseURL: 'https://simple-distributed-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simple-distributed-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU8-SY-_tSFzch4EH5N7F32gVGfU803ZY',
    appId: '1:424296832329:ios:dc3bbf3d931bf1cfe64e98',
    messagingSenderId: '424296832329',
    projectId: 'simple-distributed-database',
    databaseURL: 'https://simple-distributed-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simple-distributed-database.firebasestorage.app',
    iosClientId: '424296832329-igai84cr1mh909ctm3htind2glcramjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.factsUiUx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU8-SY-_tSFzch4EH5N7F32gVGfU803ZY',
    appId: '1:424296832329:ios:dc3bbf3d931bf1cfe64e98',
    messagingSenderId: '424296832329',
    projectId: 'simple-distributed-database',
    databaseURL: 'https://simple-distributed-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'simple-distributed-database.firebasestorage.app',
    iosClientId: '424296832329-igai84cr1mh909ctm3htind2glcramjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.factsUiUx',
  );
}
